title: Srivatsan's Resume
description: Profile, work experience, skills, projects
theme: just-the-docs

url: https://srivatsan-prabu.github.io/resume-v1/

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
